-- OpenMatch initial migration.
-- Generated by hand; the canonical regeneration command is
-- `npx prisma migrate dev --name init` once Postgres is reachable.
-- This file is committed so contributors can review schema changes in PRs.

CREATE EXTENSION IF NOT EXISTS postgis;

-- Enums
CREATE TYPE "AccountStatus"      AS ENUM ('active','paused','banned','deleted');
CREATE TYPE "VisibilityStatus"   AS ENUM ('visible','hidden');
CREATE TYPE "ModerationStatus"   AS ENUM ('clean','reviewed_ok','under_review','restricted','removed');
CREATE TYPE "Gender"             AS ENUM ('Woman','Man','NonBinary','TransWoman','TransMan','Genderqueer','Agender','Questioning','SelfDescribe','PreferNotToSay');
CREATE TYPE "RelationshipGoal"   AS ENUM ('LongTerm','LifePartner','ShortTerm','Casual','Friendship','Figuring','Marriage','NonMono','Open');
CREATE TYPE "LikesVisibility"    AS ENUM ('visible','count_only','hidden');
CREATE TYPE "SwipeDecision"      AS ENUM ('like','reject');
CREATE TYPE "LikeStatus"         AS ENUM ('active','withdrawn','matched','rejected');
CREATE TYPE "MatchStatus"        AS ENUM ('active','unmatched');
CREATE TYPE "ConversationStatus" AS ENUM ('active','closed');
CREATE TYPE "ReportStatus"       AS ENUM ('open','reviewing','resolved','dismissed');
CREATE TYPE "ModerationDecision" AS ENUM ('no_action','warning','content_removed','temporary_suspension','permanent_ban');
CREATE TYPE "AuthProvider"       AS ENUM ('apple','email','dev');

-- "User"
CREATE TABLE "User" (
    "id"             TEXT NOT NULL,
    "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"      TIMESTAMP(3) NOT NULL,
    "status"         "AccountStatus" NOT NULL DEFAULT 'active',
    "dateOfBirth"    TIMESTAMP(3) NOT NULL,
    "emailHash"      TEXT,
    "phoneHash"      TEXT,
    "authProvider"   "AuthProvider" NOT NULL,
    "authSubject"    TEXT,
    "isAgeVerified"  BOOLEAN NOT NULL DEFAULT false,
    "isBanned"       BOOLEAN NOT NULL DEFAULT false,
    "deletedAt"      TIMESTAMP(3),
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_emailHash_key"   ON "User"("emailHash");
CREATE UNIQUE INDEX "User_phoneHash_key"   ON "User"("phoneHash");
CREATE UNIQUE INDEX "User_authSubject_key" ON "User"("authSubject");
CREATE INDEX "User_status_idx" ON "User"("status");

-- "Profile"
CREATE TABLE "Profile" (
    "id"                       TEXT NOT NULL,
    "userId"                   TEXT NOT NULL,
    "displayName"              TEXT NOT NULL,
    "bio"                      TEXT NOT NULL DEFAULT '',
    "gender"                   "Gender" NOT NULL,
    "pronouns"                 TEXT,
    "ageDisplayEnabled"        BOOLEAN NOT NULL DEFAULT true,
    "location"                 geography(Point, 4326),
    "city"                     TEXT,
    "region"                   TEXT,
    "country"                  TEXT,
    "heightCm"                 INTEGER,
    "educationLevel"           TEXT,
    "college"                  TEXT,
    "jobTitle"                 TEXT,
    "companyDisplayEnabled"    BOOLEAN NOT NULL DEFAULT false,
    "company"                  TEXT,
    "relationshipGoal"         "RelationshipGoal",
    "childrenStatus"           TEXT,
    "familyPlans"              TEXT,
    "drinking"                 TEXT,
    "smoking"                  TEXT,
    "cannabis"                 TEXT,
    "exercise"                 TEXT,
    "diet"                     TEXT,
    "religion"                 TEXT,
    "politics"                 TEXT,
    "languages"                TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "interests"                TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "verificationStatus"       TEXT NOT NULL DEFAULT 'unverified',
    "visibilityStatus"         "VisibilityStatus" NOT NULL DEFAULT 'visible',
    "moderationStatus"         "ModerationStatus" NOT NULL DEFAULT 'clean',
    "prompts"                  JSONB,
    "lastActiveAt"             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt"                TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"                TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Profile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Profile_userId_key" ON "Profile"("userId");
CREATE INDEX "Profile_visibilityStatus_moderationStatus_idx" ON "Profile"("visibilityStatus","moderationStatus");
CREATE INDEX "Profile_city_idx" ON "Profile"("city");
CREATE INDEX "Profile_location_idx" ON "Profile" USING GIST ("location");
ALTER TABLE "Profile" ADD CONSTRAINT "Profile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;

-- "ProfilePhoto"
CREATE TABLE "ProfilePhoto" (
    "id"               TEXT NOT NULL,
    "profileId"        TEXT NOT NULL,
    "storageKey"       TEXT NOT NULL,
    "cdnUrl"           TEXT NOT NULL,
    "sortOrder"        INTEGER NOT NULL,
    "moderationStatus" "ModerationStatus" NOT NULL DEFAULT 'clean',
    "width"            INTEGER,
    "height"           INTEGER,
    "blurhash"         TEXT,
    "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"        TIMESTAMP(3) NOT NULL,
    CONSTRAINT "ProfilePhoto_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "ProfilePhoto_profileId_sortOrder_idx" ON "ProfilePhoto"("profileId","sortOrder");
ALTER TABLE "ProfilePhoto" ADD CONSTRAINT "ProfilePhoto_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE;

-- "Preferences"
CREATE TABLE "Preferences" (
    "id"                              TEXT NOT NULL,
    "userId"                          TEXT NOT NULL,
    "minAge"                          INTEGER NOT NULL DEFAULT 18,
    "maxAge"                          INTEGER NOT NULL DEFAULT 99,
    "maxDistanceKm"                   INTEGER NOT NULL DEFAULT 40,
    "interestedGenders"               "Gender"[] NOT NULL DEFAULT ARRAY[]::"Gender"[],
    "relationshipGoals"               "RelationshipGoal"[] NOT NULL DEFAULT ARRAY[]::"RelationshipGoal"[],
    "heightMinCm"                     INTEGER,
    "heightMaxCm"                     INTEGER,
    "educationLevels"                 TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "colleges"                        TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    "lifestyleFilters"                JSONB,
    "includeUnansweredOptionalFields" BOOLEAN NOT NULL DEFAULT true,
    "hardFilters"                     JSONB,
    "softPreferences"                 JSONB,
    "excludeIncompatibleGoals"        BOOLEAN NOT NULL DEFAULT false,
    "likesVisibility"                 "LikesVisibility" NOT NULL DEFAULT 'visible',
    "discoveryPaused"                 BOOLEAN NOT NULL DEFAULT false,
    "createdAt"                       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"                       TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Preferences_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Preferences_userId_key" ON "Preferences"("userId");
ALTER TABLE "Preferences" ADD CONSTRAINT "Preferences_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;

-- "SwipeAction"
CREATE TABLE "SwipeAction" (
    "id"                   TEXT NOT NULL,
    "viewerUserId"         TEXT NOT NULL,
    "targetUserId"         TEXT NOT NULL,
    "decision"             "SwipeDecision" NOT NULL,
    "algorithmVersion"     TEXT NOT NULL,
    "rankingConfigVersion" TEXT NOT NULL,
    "deckSessionId"        TEXT NOT NULL,
    "createdAt"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "undoneAt"             TIMESTAMP(3),
    CONSTRAINT "SwipeAction_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "SwipeAction_viewerUserId_targetUserId_idx" ON "SwipeAction"("viewerUserId","targetUserId");
CREATE INDEX "SwipeAction_targetUserId_decision_idx"     ON "SwipeAction"("targetUserId","decision");
ALTER TABLE "SwipeAction" ADD CONSTRAINT "SwipeAction_viewerUserId_fkey" FOREIGN KEY ("viewerUserId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "SwipeAction" ADD CONSTRAINT "SwipeAction_targetUserId_fkey" FOREIGN KEY ("targetUserId") REFERENCES "User"("id") ON DELETE CASCADE;

-- "Like"
CREATE TABLE "Like" (
    "id"          TEXT NOT NULL,
    "fromUserId"  TEXT NOT NULL,
    "toUserId"    TEXT NOT NULL,
    "status"      "LikeStatus" NOT NULL DEFAULT 'active',
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "withdrawnAt" TIMESTAMP(3),
    CONSTRAINT "Like_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Like_fromUserId_toUserId_key" ON "Like"("fromUserId","toUserId");
CREATE INDEX "Like_toUserId_status_idx" ON "Like"("toUserId","status");
ALTER TABLE "Like" ADD CONSTRAINT "Like_fromUserId_fkey" FOREIGN KEY ("fromUserId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Like" ADD CONSTRAINT "Like_toUserId_fkey"   FOREIGN KEY ("toUserId")   REFERENCES "User"("id") ON DELETE CASCADE;

-- "Match"
CREATE TABLE "Match" (
    "id"                TEXT NOT NULL,
    "userAId"           TEXT NOT NULL,
    "userBId"           TEXT NOT NULL,
    "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "unmatchedAt"       TIMESTAMP(3),
    "unmatchedByUserId" TEXT,
    "status"            "MatchStatus" NOT NULL DEFAULT 'active',
    CONSTRAINT "Match_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Match_userAId_userBId_key" ON "Match"("userAId","userBId");
CREATE INDEX "Match_userAId_status_idx" ON "Match"("userAId","status");
CREATE INDEX "Match_userBId_status_idx" ON "Match"("userBId","status");
ALTER TABLE "Match" ADD CONSTRAINT "Match_userAId_fkey"           FOREIGN KEY ("userAId")           REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Match" ADD CONSTRAINT "Match_userBId_fkey"           FOREIGN KEY ("userBId")           REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Match" ADD CONSTRAINT "Match_unmatchedByUserId_fkey" FOREIGN KEY ("unmatchedByUserId") REFERENCES "User"("id");

-- "Conversation"
CREATE TABLE "Conversation" (
    "id"        TEXT NOT NULL,
    "matchId"   TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "status"    "ConversationStatus" NOT NULL DEFAULT 'active',
    CONSTRAINT "Conversation_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Conversation_matchId_key" ON "Conversation"("matchId");
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_matchId_fkey" FOREIGN KEY ("matchId") REFERENCES "Match"("id") ON DELETE CASCADE;

-- "Message"
CREATE TABLE "Message" (
    "id"               TEXT NOT NULL,
    "conversationId"   TEXT NOT NULL,
    "senderUserId"     TEXT NOT NULL,
    "body"             TEXT NOT NULL,
    "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deliveredAt"      TIMESTAMP(3),
    "readAt"           TIMESTAMP(3),
    "deletedAt"        TIMESTAMP(3),
    "moderationStatus" "ModerationStatus" NOT NULL DEFAULT 'clean',
    CONSTRAINT "Message_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Message_conversationId_createdAt_idx" ON "Message"("conversationId","createdAt");
ALTER TABLE "Message" ADD CONSTRAINT "Message_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_senderUserId_fkey"   FOREIGN KEY ("senderUserId")   REFERENCES "User"("id") ON DELETE CASCADE;

-- "Block"
CREATE TABLE "Block" (
    "id"            TEXT NOT NULL,
    "blockerUserId" TEXT NOT NULL,
    "blockedUserId" TEXT NOT NULL,
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Block_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Block_blockerUserId_blockedUserId_key" ON "Block"("blockerUserId","blockedUserId");
CREATE INDEX "Block_blockedUserId_idx" ON "Block"("blockedUserId");
ALTER TABLE "Block" ADD CONSTRAINT "Block_blockerUserId_fkey" FOREIGN KEY ("blockerUserId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Block" ADD CONSTRAINT "Block_blockedUserId_fkey" FOREIGN KEY ("blockedUserId") REFERENCES "User"("id") ON DELETE CASCADE;

-- "Report"
CREATE TABLE "Report" (
    "id"                TEXT NOT NULL,
    "reporterUserId"    TEXT NOT NULL,
    "reportedUserId"    TEXT NOT NULL,
    "reportedProfileId" TEXT,
    "reportedMessageId" TEXT,
    "reason"            TEXT NOT NULL,
    "details"           TEXT,
    "status"            "ReportStatus" NOT NULL DEFAULT 'open',
    "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt"        TIMESTAMP(3),
    "moderatorId"       TEXT,
    "resolution"        "ModerationDecision",
    CONSTRAINT "Report_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Report_status_createdAt_idx" ON "Report"("status","createdAt");
ALTER TABLE "Report" ADD CONSTRAINT "Report_reporterUserId_fkey" FOREIGN KEY ("reporterUserId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_reportedUserId_fkey" FOREIGN KEY ("reportedUserId") REFERENCES "User"("id") ON DELETE CASCADE;

-- "Session"
CREATE TABLE "Session" (
    "id"           TEXT NOT NULL,
    "userId"       TEXT NOT NULL,
    "refreshToken" TEXT NOT NULL,
    "userAgent"    TEXT,
    "ipHash"       TEXT,
    "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt"    TIMESTAMP(3) NOT NULL,
    "revokedAt"    TIMESTAMP(3),
    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Session_refreshToken_key" ON "Session"("refreshToken");
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;

-- "AuthChallenge"
CREATE TABLE "AuthChallenge" (
    "id"         TEXT NOT NULL,
    "userId"     TEXT,
    "email"      TEXT,
    "tokenHash"  TEXT NOT NULL,
    "expiresAt"  TIMESTAMP(3) NOT NULL,
    "consumedAt" TIMESTAMP(3),
    "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuthChallenge_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "AuthChallenge_tokenHash_key" ON "AuthChallenge"("tokenHash");
ALTER TABLE "AuthChallenge" ADD CONSTRAINT "AuthChallenge_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;

-- "DeviceToken"
CREATE TABLE "DeviceToken" (
    "id"        TEXT NOT NULL,
    "userId"    TEXT NOT NULL,
    "token"     TEXT NOT NULL,
    "platform"  TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DeviceToken_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "DeviceToken_token_key" ON "DeviceToken"("token");
ALTER TABLE "DeviceToken" ADD CONSTRAINT "DeviceToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;

-- "AlgorithmAuditRecord"
CREATE TABLE "AlgorithmAuditRecord" (
    "id"                   TEXT NOT NULL,
    "algorithmVersion"     TEXT NOT NULL,
    "rankingConfigVersion" TEXT NOT NULL,
    "changedBy"            TEXT NOT NULL,
    "changeSummary"        TEXT NOT NULL,
    "publicChangelogUrl"   TEXT,
    "createdAt"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AlgorithmAuditRecord_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "AlgorithmAuditRecord_createdAt_idx" ON "AlgorithmAuditRecord"("createdAt");
