#!/usr/bin/env node

// gen-sdk.mjs — generate a TypeScript client from the backend's
// OpenAPI 3.1 export. Output lands in sdk/typescript/.
//
// How it works:
//   1. Locate the OpenAPI document. By default we hit the running
//      backend at $OPENAPI_URL (default http://localhost:8080/openapi.json).
//      If that's not reachable but $OPENAPI_FILE points at a JSON
//      file, we use that instead.
//   2. Snapshot the doc to sdk/openapi.json so the SDK is regenerable
//      from a known input without the backend running.
//   3. Run `openapi-typescript` to produce sdk/typescript/schema.d.ts
//      (typed `paths` + `components` interfaces).
//   4. Emit a tiny fetch-based client wrapper that uses the schema.
//
// We deliberately avoid openapi-generator's TypeScript template — it
// drags in a Java runtime and produces axios-flavoured output. The
// goal here is a zero-runtime-deps `fetch` client that works in
// browsers, Node 20+, and React Native.
//
// The Swift SDK is intentionally NOT generated here. openapi-generator's
// Swift template requires Java; ROADMAP.md tracks this as follow-up.
// Forks that need Swift today can run:
//   npx @openapitools/openapi-generator-cli generate \
//     -i sdk/openapi.json -g swift5 -o sdk/swift

import { spawn } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, "..");

const OPENAPI_URL = process.env.OPENAPI_URL ?? "http://localhost:8080/openapi.json";
const OPENAPI_FILE = process.env.OPENAPI_FILE ?? null;
const OUT_DIR = resolve(ROOT, "sdk");
const TS_DIR = resolve(OUT_DIR, "typescript");

function run(cmd, args, opts = {}) {
  return new Promise((resolveExec, rejectExec) => {
    const child = spawn(cmd, args, { stdio: "inherit", shell: false, ...opts });
    child.on("error", rejectExec);
    child.on("exit", (code) => {
      if (code === 0) resolveExec();
      else rejectExec(new Error(`${cmd} ${args.join(" ")} exited with ${code}`));
    });
  });
}

async function loadOpenApi() {
  if (OPENAPI_FILE) {
    console.log(`📄 Loading OpenAPI from file: ${OPENAPI_FILE}`);
    const txt = await readFile(OPENAPI_FILE, "utf8");
    return JSON.parse(txt);
  }
  console.log(`📡 Fetching OpenAPI from: ${OPENAPI_URL}`);
  let res;
  try {
    res = await fetch(OPENAPI_URL);
  } catch (e) {
    throw new Error(
      `Could not reach ${OPENAPI_URL}.\nIs the backend running? Try \`make up-services && npm run dev -w @openmatch/backend\`.\nOr set OPENAPI_FILE=path/to/openapi.json to use a snapshot.\n(${e.message})`,
    );
  }
  if (!res.ok) {
    throw new Error(`${OPENAPI_URL} returned ${res.status} ${res.statusText}`);
  }
  return res.json();
}

function clientWrapper() {
  return `// Auto-generated by scripts/gen-sdk.mjs — DO NOT EDIT.
// A thin, typed wrapper around \`fetch\` that uses the OpenAPI schema
// in \`./schema.d.ts\`. Zero runtime dependencies.
//
// Usage:
//   import { createClient } from "@openmatch/sdk";
//   const om = createClient({ baseUrl: "https://api.openmatch.app", token: "..." });
//   const res = await om.GET("/api/v1/transparency/algorithm/current");
//
// Regenerate after schema changes: \`npm run gen:sdk\`.

import type { paths } from "./schema";

export type Paths = paths;

export interface ClientOptions {
  baseUrl: string;
  /** Bearer token. If omitted, requests are sent unauthenticated. */
  token?: string | (() => string | Promise<string>);
  /** Extra headers applied to every request. */
  headers?: Record<string, string>;
  /** Provide a custom fetch implementation (Node 18+, browsers, RN). */
  fetch?: typeof fetch;
}

type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

function buildUrl(baseUrl: string, path: string, params: Record<string, unknown> | undefined): string {
  let p = path;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      p = p.replace(\`{\${k}}\`, encodeURIComponent(String(v)));
    }
  }
  return baseUrl.replace(/\\/+$/, "") + p;
}

async function resolveToken(t: ClientOptions["token"]): Promise<string | undefined> {
  if (typeof t === "function") return await t();
  return t;
}

export function createClient(opts: ClientOptions) {
  const f = opts.fetch ?? globalThis.fetch;
  if (!f) {
    throw new Error("No fetch implementation available. Provide one via { fetch }.");
  }

  async function request<T = unknown>(
    method: Method,
    path: string,
    init: {
      params?: Record<string, unknown>;
      query?: Record<string, string | number | boolean | undefined>;
      body?: unknown;
      headers?: Record<string, string>;
    } = {},
  ): Promise<{ data: T; response: Response }> {
    const token = await resolveToken(opts.token);
    const headers: Record<string, string> = {
      Accept: "application/json",
      ...(opts.headers ?? {}),
      ...(init.headers ?? {}),
    };
    if (token) headers["Authorization"] = \`Bearer \${token}\`;
    let url = buildUrl(opts.baseUrl, path, init.params);
    if (init.query) {
      const qs = Object.entries(init.query)
        .filter(([, v]) => v !== undefined)
        .map(([k, v]) => \`\${encodeURIComponent(k)}=\${encodeURIComponent(String(v))}\`)
        .join("&");
      if (qs) url += (url.includes("?") ? "&" : "?") + qs;
    }
    const reqInit: RequestInit = { method, headers };
    if (init.body !== undefined) {
      headers["Content-Type"] ??= "application/json";
      reqInit.body = typeof init.body === "string" ? init.body : JSON.stringify(init.body);
    }
    const response = await f(url, reqInit);
    let data: T;
    const ct = response.headers.get("content-type") ?? "";
    if (ct.includes("application/json")) {
      data = (await response.json()) as T;
    } else {
      data = (await response.text()) as unknown as T;
    }
    if (!response.ok) {
      const err = new Error(
        \`\${method} \${path} failed: \${response.status} \${response.statusText}\`,
      );
      Object.assign(err, { status: response.status, data, response });
      throw err;
    }
    return { data, response };
  }

  return {
    GET: <P extends keyof paths>(path: P, init?: Parameters<typeof request>[2]) => request("GET", path as string, init),
    POST: <P extends keyof paths>(path: P, init?: Parameters<typeof request>[2]) => request("POST", path as string, init),
    PUT: <P extends keyof paths>(path: P, init?: Parameters<typeof request>[2]) => request("PUT", path as string, init),
    PATCH: <P extends keyof paths>(path: P, init?: Parameters<typeof request>[2]) => request("PATCH", path as string, init),
    DELETE: <P extends keyof paths>(path: P, init?: Parameters<typeof request>[2]) => request("DELETE", path as string, init),
    /** Escape hatch for routes not yet in the schema. */
    request,
  };
}
`;
}

function clientReadme(spec) {
  const version = spec.info?.version ?? "unknown";
  const title = spec.info?.title ?? "OpenMatch";
  return `# @openmatch/sdk (TypeScript)

Auto-generated TypeScript client for the **${title}** API
(schema version \`${version}\`).

Generated by [\`scripts/gen-sdk.mjs\`](../scripts/gen-sdk.mjs) from the
backend's OpenAPI 3.1 export at \`/openapi.json\`. Regenerate after
schema changes:

\`\`\`bash
npm run gen:sdk
\`\`\`

## Install

This SDK is shipped as part of the OpenMatch monorepo. To use it from
a downstream project, copy the \`sdk/typescript/\` directory or
publish it as a private npm package.

## Usage

\`\`\`ts
import { createClient } from "@openmatch/sdk";

const om = createClient({
  baseUrl: "https://api.openmatch.app",
  token: "your-access-token",
});

const { data } = await om.GET("/api/v1/transparency/algorithm/current");
//        ^? typed against schema.d.ts
\`\`\`

The client is a thin wrapper around \`fetch\`. It works in:

- Node 20+
- All modern browsers
- React Native (provide a polyfill if your RN version doesn't ship fetch)
- Bun, Deno (pass \`{ fetch: globalThis.fetch }\` explicitly if needed)

## Files

- \`schema.d.ts\` — generated types from \`openapi-typescript\`.
- \`index.ts\` — the \`createClient\` wrapper.
- \`../openapi.json\` — snapshot of the source document.

## Regenerating

The schema lives at:

- live backend: \`http://localhost:8080/openapi.json\`
- snapshot: \`sdk/openapi.json\`

\`\`\`bash
# Live regeneration (backend must be running):
npm run gen:sdk

# Snapshot regeneration (offline):
OPENAPI_FILE=sdk/openapi.json npm run gen:sdk
\`\`\`

## Swift

The Swift SDK is not generated by this script because
openapi-generator's Swift template requires a Java toolchain. Forks
that need a typed Swift client can run:

\`\`\`bash
npx @openapitools/openapi-generator-cli generate \\
  -i sdk/openapi.json -g swift5 -o sdk/swift
\`\`\`

Tracked in [\`ROADMAP.md\`](../../ROADMAP.md).
`;
}

// openapi-typescript ships a CLI we can invoke via npx without adding
// it to the workspace dependency graph. We pin a known-good major to
// avoid surprises.
async function generateSchema() {
  const args = [
    "--yes",
    "openapi-typescript@^7",
    resolve(OUT_DIR, "openapi.json"),
    "--output",
    resolve(TS_DIR, "schema.d.ts"),
  ];
  console.log(`🔧 Running: npx ${args.join(" ")}`);
  await run("npx", args);
}

async function main() {
  console.log("OpenMatch SDK generator");
  console.log("=======================\n");

  const spec = await loadOpenApi();
  if (!spec.openapi) {
    throw new Error(`Loaded document is not an OpenAPI spec (no \`openapi\` field).`);
  }
  console.log(
    `📘 Loaded ${spec.info?.title ?? "OpenAPI"} v${spec.info?.version ?? "?"} (${
      Object.keys(spec.paths ?? {}).length
    } paths)`,
  );

  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(TS_DIR, { recursive: true });

  const snapshotPath = resolve(OUT_DIR, "openapi.json");
  await writeFile(snapshotPath, `${JSON.stringify(spec, null, 2)}\n`, "utf8");
  console.log(`💾 Snapshot → ${snapshotPath}`);

  await generateSchema();
  console.log(`📐 Schema    → ${resolve(TS_DIR, "schema.d.ts")}`);

  const indexPath = resolve(TS_DIR, "index.ts");
  await writeFile(indexPath, clientWrapper(), "utf8");
  console.log(`🧩 Client    → ${indexPath}`);

  const readmePath = resolve(TS_DIR, "README.md");
  await writeFile(readmePath, clientReadme(spec), "utf8");
  console.log(`📝 README    → ${readmePath}`);

  console.log("\n✅ SDK generated. Review the diff and commit.\n");
}

main().catch((err) => {
  console.error(`\n✖ ${err.message}`);
  process.exit(1);
});
